### PR TITLE
fix: Minor grammatical fixes

### PR DESCRIPTION
**Pull request by jamesgeorge007**
- Fixed couple of typos.
- Grammatical tweaks.

### CODE REVIEW

**Review by DanielRuf — APPROVED** [review]

**Comment by anikethsaha** [comment]
@jamesgeorge007 can you squash the commits !!!

**Review by anikethsaha — CHANGES_REQUESTED** [review]
Need squashing

**Comment by DanielRuf** [comment]
> Need squashing

Not squash (we don't need the same message multiple lines) but rebase (with `fixup`).

**Comment by DanielRuf** [comment]
I'll try to rebase the commits onto one.

**Comment by DanielRuf** [comment]
Please run `git rebase -i HEAD~12` and use `pick` for the first at the top and `fixup` for all others.

**Comment by anikethsaha** [comment]
> Please run `git rebase -i HEAD~12` and use `pick` for the first at the top and `fixup` for all others.

Yea...this is much better 👍

**Review by rishabh3112 — APPROVED** [review]
Changes looks fine. Just take care for commits as suggested by others

**Review by DanielRuf — APPROVED** [review]

**Comment by DanielRuf** [comment]
> [jamesgeorge007](/jamesgeorge007) merged commit [`aa5d5dd`](/webpack/changelog-v5/commit/aa5d5ddae18f1849fc6d981cd86a500672c14d26) into master [vor 8 Minuten](/webpack/changelog-v5/pull/17#event-2926782758)

Please do not merge yourself. Reviewers or others should do this.

**Comment by DanielRuf** [comment]
Also please create a branch on your fork next time to prevent that we have many branches here in this repo.

**Comment by jamesgeorge007** [comment]
> > [jamesgeorge007](/jamesgeorge007) merged commit [`aa5d5dd`](/webpack/changelog-v5/commit/aa5d5ddae18f1849fc6d981cd86a500672c14d26) into master [vor 8 Minuten](/webpack/changelog-v5/pull/17#event-2926782758)
> 
> Please do not merge yourself. Reviewers or others should do this.

I did this as it was a very minimalistic update and also Ig people are given write access to the repo for the same reason. Apologies if this wasn't intended :pray:

**Comment by jamesgeorge007** [comment]
> Also please create a branch on your fork next time to prevent that we have many branches here in this repo.

It is being deleted once the PR gets merged. But anyways :+1:

**Pull request merged**
