### PR TITLE
Webpack5 supports ES6

### PR DESCRIPTION
**Pull request by rajatkumar**
Minor typo - ES2015 is ES6 and webpack 5 now supports ES6/ES2015 code.

### CODE REVIEW

**Comment by DanielRuf** [comment]
I think it was correct. Output can be either ES5 or ES2015 (and newer).

**Comment by rajatkumar** [comment]
Maybe a better way to express this will be : **webpack 5 can generate both ES5 and ES6/ES2015 code now.** The default configuration will generate ES2015 code. If you need to support older browser (like IE11), you can decrease this to `output.ecmaVersion: 5`

**Comment by ematipico** [comment]
Also the previous paragraph is misleading. It should state "minimum" version and not maximum version, I think.

**Review by ematipico — APPROVED** [review]

**Comment by sokra** [comment]
> It should state "minimum" version and not maximum version, I think.

Depends on from which side you look at it.

It generates code with the specified version or lower. -> maximum

The browser need to support the specified version or higher. -> minimum

**Pull request merged**
